# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    verbosityRestore: 'Detailed'
    packagesDirectory: '$(Build.SourcesDirectory)\packages'

- task: VSBuild@1
  displayName: 'Clean and Build Library'
  inputs:
    solution: 'MySnipItTool/DrawingShapesLibrary/DrawingShapesLibrary.csproj'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Clean;Build'

- task: VSBuild@1
  displayName: 'Build WPF Project'
  inputs:
    solution: 'MySnipItTool/MySnipItTool/MySnipItTool.csproj'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Create Zip File'
  inputs:
    targetType: 'inline'
    script: |
      echo "Zipping files..."
      $outputPath = '$(Build.ArtifactStagingDirectory)\MySnipItTool.zip'
      $binPath = '$(Build.SourcesDirectory)\PaintingDetailsManager\bin'

      # Remove existing zip file if it exists
      if (Test-Path $outputPath) {
        Remove-Item $outputPath
      }

      # List the contents of the Release directory inside bin for debugging
      Get-ChildItem -Path $binPath -Recurse

      # Check if bin\Release folder exists
      if (-Not (Test-Path $binPath)) {
        Write-Host "Error: Bin/Release directory does not exist."
        exit 1
      }

      echo "Zip file created at: $outputPath"

- task: CmdLine@2
  displayName: 'Check Zip File Contents'
  inputs:
    script: |
      echo "Checking contents of the zip file..."
      tar -tf "$(Build.ArtifactStagingDirectory)\MySnipItTool.zip"


- task: PublishBuildArtifacts@1
  displayName: 'Publish WPF Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\MySnipItTool.zip'
    ArtifactName: 'PaintingDetailsManager'
    publishLocation: 'Container'
    ArtifactType: 'Container'




- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'zacharywatson1129'
    repositoryName: 'zacharywatson1129/MySnipItTool'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    assets: '$(Build.ArtifactStagingDirectory)\MySnipItTool.zip'  # Point to your zip